version: '3.8'

services:
  frontend:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}  # Para build time (vite)
    ports:
      - "3000:80"
    environment:
      API_URL: ${API_URL}  # Para runtime (nginx env.js)
    restart: unless-stopped   