services:
  web:
    build: .
    container_name: store-frontend
    ports:
      - "5173:80"      # abre en http://localhost:5173
    environment:
      API_BASE_URL: "http://localhost:8000"
      APP_NAME: "Store Service"
      NODE_ENV: "production"
    restart: unless-stopped
